use_frameworks!

target 'Tableable_Example' do
  pod 'Tableable', :path => '../'

  target 'Tableable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
